"""empty message

Revision ID: 734d533634ce
Revises: d145a6773527
Create Date: 2022-05-08 21:22:09.710504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734d533634ce'
down_revision = 'd145a6773527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('post', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
