version: '3'


services:

  app:
    build:
      context: ./app
    container_name: flask
    command: gunicorn --bind 0.0.0.0:5000 run:app
    environment:
      - DATABASE_URL=postgresql://user:password@host/db_name
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - host

  host:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db_name
    volumes:
      - ./pg_db:/var/lib/postgresql

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
