version: '3'


services:

  app:
    build:
      context: ./app
    container_name: flask
    command: gunicorn --bind 0.0.0.0:5000 run:app
    environment:
      - DATABASE_URL=postgresql://postgres:123@localhost/blog_db
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - localhost

  localhost:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=123
      - POSTGRES_DB=blog_db
    volumes:
      - ./pg_db:/var/lib/postgresql

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
