version: '3'


services:

  app:
    build:
      context: ./app
    container_name: flask
    command: gunicorn --bind 0.0.0.0:5000 run:app
    env_file:
      - .flaskenv
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:13
    container_name: db
    env_file:
      - .dbenv
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - app
