version: '3'


services:

  app:
    build: ./app
    container_name: flask
    ports:
      - "5000:5000"
    env_file:
      - .flaskenv
    command: gunicorn --bind 0.0.0.0:5000 run:app
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .dbenv
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    restart: always

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - app
